### PR TITLE
Adding the Model Registry Tenancy Model

### PR DESCRIPTION
**Pull request by rareddy**
Adding Model Registry's Tenancy and RBAC Designs 

## Description
This commit adds the details about the Model Registry deployment model in the OpenShift AI, then later describes how it uses Service Mesh and Authorino to support RBAC, mTLS and show the tenancy model where a single model registry can be shared by more than a single project in ODH.

- [x ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by rareddy** [comment]
@dhirajsb can you please review and approve?

**Comment by dhirajsb** [comment]
@rareddy is this all the content of the ADR docs I had put together earlier? Is there any way to keep the discussions from the docs? Some of them kinda explained the motivations in the design.

**Comment by rareddy** [comment]
I took what is the current implementation of it. Here we only need to show that. If you want we can refer to full document.

**Comment by dhirajsb** [comment]
I need to update some diagrams based on the current implementation. I'm working on a PR for it now.

**Comment by dhirajsb** [comment]
I opened a PR on your repo https://github.com/rareddy/architecture-decision-records/pull/1 with the updates.

**Comment by rareddy** [comment]
@etirelli Can you approve this PR please? Thank you.

**Review by dhirajsb — APPROVED** [review]
/lgtm

**Review by etirelli — APPROVED** [review]

**Pull request merged**
